import { galleryCategories } from "../data/gallery.js";
const PAGE_SIZE=12;
const grid=document.getElementById("gallery-grid");
const tabs=[...document.querySelectorAll(".gallery-tab")];
let activeCategory="blouses",currentPage=1;
function ensureLightbox(){let box=document.querySelector(".lightbox");if(box)return box;box=document.createElement("div");box.className="lightbox";box.innerHTML='<button class="lightbox-close" aria-label="Close image">×</button><img alt="Expanded gallery image">';document.body.appendChild(box);box.addEventListener("click",e=>{if(e.target===box)box.classList.remove("open")});box.querySelector(".lightbox-close").onclick=()=>box.classList.remove("open");document.addEventListener("keydown",e=>{if(e.key==="Escape")box.classList.remove("open")});return box}
const lightbox=ensureLightbox();
function render(category=activeCategory,page=1){activeCategory=category;currentPage=page;const images=galleryCategories[category]||[],pages=Math.max(1,Math.ceil(images.length/PAGE_SIZE)),safe=Math.min(page,pages),start=(safe-1)*PAGE_SIZE,visible=images.slice(start,start+PAGE_SIZE);grid.innerHTML="";
if(!visible.length){grid.innerHTML='<div class="gallery-empty"><strong>Collection coming soon.</strong><span>We are curating this collection.</span></div>';return}
visible.forEach((src,i)=>{const button=document.createElement("button");button.type="button";button.className="google-gallery-item";const img=document.createElement("img");img.src=src;img.alt=`AA Embroidery Work — ${category} ${start+i+1}`;img.loading="lazy";button.appendChild(img);button.onclick=()=>{const big=lightbox.querySelector("img");big.src=src;big.alt=img.alt;lightbox.classList.add("open")};grid.appendChild(button)});
if(pages>1){const nav=document.createElement("div");nav.className="gallery-pagination";nav.innerHTML=Array.from({length:pages},(_,i)=>'<button class="'+(i+1===safe?'active':'')+'" data-p="'+(i+1)+'">'+(i+1)+'</button>').join("");nav.querySelectorAll("button").forEach(b=>b.onclick=()=>render(activeCategory,+b.dataset.p));grid.after(nav)}}
tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>{t.classList.remove("active");t.setAttribute("aria-selected","false")});tab.classList.add("active");tab.setAttribute("aria-selected","true");render(tab.dataset.galleryCategory,1)}));render();